- name: Restart Postgres
  become: yes
  service: name=postgresql state=restarted

- name: restart nginx
  service: name=nginx state=restarted

- name: restart gunicorn
  service: name=gunicorn state=restarted